/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presente;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.PreparedStatement;

public class Pedidos extends javax.swing.JFrame {

    ConexionMys con = new ConexionMys();
    Connection cn = con.conectar();

    public Pedidos() {
        initComponents();
    }

    private void mostrarPedidos() {
        // Se crea un modelo de tabla por defecto
        DefaultTableModel modelo = new DefaultTableModel();

        // Se añaden las columnas al modelo
        modelo.addColumn("NoPedido");
        modelo.addColumn("Equipo");
        modelo.addColumn("ModeloUniforme");
        modelo.addColumn("NoUniformes");
        modelo.addColumn("Precio");

        // Se establece el modelo en la tabla jTable1
        jTable1.setModel(modelo);

        // Consulta SQL para obtener los pedidos
        String consultaSql = "SELECT * FROM pedidos";

        // Arreglo para almacenar los datos de cada fila
        String data[] = new String[5];

        // Declaración de la declaración de SQL
        Statement st;

        try {
            // Se crea la declaración SQL
            st = cn.createStatement();

            // Se ejecuta la consulta
            ResultSet rs = st.executeQuery(consultaSql);

            // Se recorre el conjunto de resultados
            while (rs.next()) {
                // Se obtiene el valor de la columna "NoPedido"
                data[0] = rs.getString(1);

                // Validar que NoPedido sea un número
                if (isNumeric(rs.getString(1))) {
                    // Si es un número, se asigna el valor
                    data[0] = rs.getString(1);
                } else {
                    // Si NoPedido no es un número, se asigna un valor por defecto o muestra un mensaje de error
                    data[0] = "Caracteres Inválidos";
                }

                // Se obtienen los valores de las otras columnas
                data[1] = rs.getString(2);
                data[2] = rs.getString(3);
                data[3] = rs.getString(4);

                // Validar que Precio sea un número
                if (isNumeric(rs.getString(5))) {
                    // Si es un número, se asigna el valor
                    data[4] = rs.getString(5);
                } else {
                    // Si Precio no es un número, se asigna un valor por defecto o muestra un mensaje de error
                    data[4] = "Caracteres Inválidos";
                }

                // Se agrega la fila al modelo de la tabla
                modelo.addRow(data);
            }
        } catch (SQLException e) {
            // Se imprime un mensaje de error en caso de una excepción SQL
            System.out.println("Error: " + e);
        }
    }

    private boolean isNumeric(String str) {
        try {
            Double.parseDouble(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    public DefaultTableModel obtenerDatosPedidos() {

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("NoPedido");
        modelo.addColumn("Equipo");  // Nueva columna de tipo VARCHAR
        modelo.addColumn("ModeloUniforme");
        modelo.addColumn("NoUniformes");
        modelo.addColumn("Precio");

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM pedidos");

            while (rs.next()) {
                Object[] data = {
                    rs.getString(1),
                    rs.getString(2), // Ajustar al nombre real de la columna en la base de datos
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5)
                };
                modelo.addRow(data);
            }
        } catch (SQLException e) {
            System.out.println("Error al obtener datos de pedidos: " + e);
        }

        return modelo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNoPedido = new javax.swing.JTextField();
        txtModeloUniforme = new javax.swing.JTextField();
        txtNoUniformes = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnCompletado = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtEquipo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jPopupMenu1.setComponentPopupMenu(jPopupMenu1);
        jPopupMenu1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPopupMenu1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jMenuItem1.setText("ELIMINAR");
        jMenuItem1.setComponentPopupMenu(jPopupMenu1);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jTable1ComponentHidden(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(204, 153, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setText("NoPedido");

        jLabel2.setText("Modelo");

        jLabel3.setText("NoUniformes");

        jLabel4.setText("Precio");

        txtNoPedido.setEditable(false);

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnCompletado.setForeground(new java.awt.Color(0, 153, 0));
        btnCompletado.setText("-Vendido-");
        btnCompletado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompletadoActionPerformed(evt);
            }
        });

        jLabel5.setText("Equipo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnRegistrar)
                .addGap(31, 31, 31)
                .addComponent(btnActualizar)
                .addGap(30, 30, 30)
                .addComponent(btnMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnCompletado)
                .addGap(18, 18, 18))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(txtModeloUniforme)
                            .addComponent(txtNoUniformes)
                            .addComponent(txtPrecio))))
                .addGap(67, 67, 67))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtModeloUniforme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNoUniformes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnActualizar)
                    .addComponent(btnMostrar)
                    .addComponent(btnCompletado))
                .addGap(17, 17, 17))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/IMGpedidos(1).jpg"))); // NOI18N

        jButton1.setText("REGRESAR");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 68, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement ps = cn.prepareStatement("INSERT INTO pedidos (Equipo, ModeloUniforme, NoUniformes, Precio) VALUES (?,?,?,?)");
            ps.setString(1, txtEquipo.getText());  // Equipo va a la posición 1
            ps.setString(2, txtModeloUniforme.getText());   // Cadena vacía o null, dependiendo de tu configuración de base de datos, va a la posición 2 (ModeloUniforme)
            ps.setInt(3, Integer.parseInt(txtNoUniformes.getText()));
            ps.setDouble(4, Double.parseDouble(txtPrecio.getText()));
            ps.executeUpdate();

            JOptionPane.showMessageDialog(rootPane, "Datos guardados correctamente");
            mostrarPedidos();

            // Limpiar los campos después de la inserción
            txtEquipo.setText("");
            txtModeloUniforme.setText("");
            txtNoUniformes.setText("");
            txtPrecio.setText("");
        } catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Error al registrar pedido" + e);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        mostrarPedidos();
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int fila = jTable1.getSelectedRow();
        if (fila >= 0) {
            this.txtNoPedido.setText(jTable1.getValueAt(fila, 0).toString());
            this.txtEquipo.setText(jTable1.getValueAt(fila, 1).toString());
            this.txtModeloUniforme.setText(jTable1.getValueAt(fila, 2).toString());
            this.txtNoUniformes.setText(jTable1.getValueAt(fila, 3).toString());
            this.txtPrecio.setText(jTable1.getValueAt(fila, 4).toString());// Ajusta el índice según la posición de Precio en tu tabla
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecciona una fila primero.");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement ps = cn.prepareStatement("UPDATE pedidos SET Equipo=?, ModeloUniforme=?, NoUniformes=?, Precio=? WHERE NoPedido=?");
            ps.setString(1, txtEquipo.getText());  // Cambiado a la posición 1
            ps.setString(2, txtModeloUniforme.getText());  // Cambiado a la posición 2
            ps.setInt(3, Integer.parseInt(txtNoUniformes.getText()));
            ps.setDouble(4, Double.parseDouble(txtPrecio.getText()));
            ps.setDouble(5, Integer.parseInt(txtNoPedido.getText()));

            int indice = ps.executeUpdate();

            if (indice > 0) {
                JOptionPane.showMessageDialog(rootPane, "Datos actualizados correctamente");
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se seleccionó una fila");
            }
        } catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Error al actualizar datos: " + e);
        }

// Limpiar los campos después de la actualización
        txtNoPedido.setText("");
        txtEquipo.setText("");
        txtModeloUniforme.setText("");
        txtNoUniformes.setText("");
        txtPrecio.setText("");
        mostrarPedidos();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jPopupMenu1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPopupMenu1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPopupMenu1AncestorAdded

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement ps = cn.prepareStatement("DELETE FROM pedidos WHERE NoPedido=?");
            ps.setInt(1, Integer.parseInt(txtNoPedido.getText()));
            int indice = ps.executeUpdate();

            if (indice > 0) {
                mostrarPedidos();
                // Limpiar los campos después de la eliminación
                txtNoPedido.setText("");
                txtEquipo.setText("");
                txtModeloUniforme.setText("");
                txtNoUniformes.setText("");
                txtPrecio.setText("");
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se seleccionó una fila");
            }
        } catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Error al eliminar datos: " + e);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTable1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1ComponentHidden

    private void btnCompletadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompletadoActionPerformed
        // TODO add your handling code here:
        String noPedido = txtNoPedido.getText();
        String equipo = txtEquipo.getText();
        String modeloUniforme = txtModeloUniforme.getText();
        String noUniformes = txtNoUniformes.getText();
        String precio = txtPrecio.getText();

        // Abrimos la ventana RegistroVentas y agregamos el registro al historial
        RegistroVentas registroVentas = new RegistroVentas();
        registroVentas.agregarRegistro(noPedido, modeloUniforme, noUniformes, precio);
        registroVentas.setVisible(true);

        // Eliminamos el registro de la tabla pedidos
        try {
            PreparedStatement ps = cn.prepareStatement("DELETE FROM pedidos WHERE NoPedido=?");
            ps.setInt(1, Integer.parseInt(noPedido));
            int indice = ps.executeUpdate();

            if (indice > 0) {
                mostrarPedidos();
                // Limpiar los campos después de la eliminación
                txtNoPedido.setText("");
                txtEquipo.setText("");
                txtModeloUniforme.setText("");
                txtNoUniformes.setText("");
                txtPrecio.setText("");
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se seleccionó una fila");
            }
        } catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Error al eliminar datos: " + e);
        }

    }//GEN-LAST:event_btnCompletadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCompletado;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtEquipo;
    private javax.swing.JTextField txtModeloUniforme;
    private javax.swing.JTextField txtNoPedido;
    private javax.swing.JTextField txtNoUniformes;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
